#!/usr/bin/env python3
"""
Fix text alignment in Excalidraw files generated by excalidraw-cli.

The CLI has two bugs:
1. Text labels overflow their parent shapes (shapes are too narrow)
2. Text elements have no containerId, so Excalidraw treats them as free-floating

This script fixes both by:
- Expanding shapes to fit their text (+ padding)
- Binding text to shapes via containerId / boundElements
- Re-centering text within the (now correctly sized) shape

Usage:
    python3 fix_text_alignment.py <file.excalidraw>
"""

import json
import sys

PADDING_X = 40
PADDING_Y = 20
MIN_HEIGHT = 60


def fix_text_alignment(filepath):
    with open(filepath, 'r') as f:
        data = json.load(f)

    elements = data['elements']
    fixed_count = 0

    i = 0
    while i < len(elements) - 1:
        shape = elements[i]
        text = elements[i + 1]

        if shape['type'] in ['rectangle', 'ellipse', 'diamond'] and text['type'] == 'text':
            shape_id = shape['id']
            text_id = text['id']
            text_w = text.get('width', 0)
            text_h = text.get('height', 0)

            # Expand shape to fit text
            new_w = max(shape['width'], text_w + PADDING_X)
            new_h = max(shape['height'], text_h + PADDING_Y, MIN_HEIGHT)

            # Adjust x so the shape stays centered on its original center
            old_cx = shape['x'] + shape['width'] / 2
            old_cy = shape['y'] + shape['height'] / 2
            shape['x'] = old_cx - new_w / 2
            shape['y'] = old_cy - new_h / 2
            shape['width'] = new_w
            shape['height'] = new_h

            # Bind text to shape (fixes Excalidraw rendering)
            text['containerId'] = shape_id
            text['textAlign'] = 'center'
            text['verticalAlign'] = 'middle'

            if 'boundElements' not in shape or shape['boundElements'] is None:
                shape['boundElements'] = []
            if not any(be.get('id') == text_id for be in shape['boundElements']):
                shape['boundElements'].append({'type': 'text', 'id': text_id})

            # Re-center text within the expanded shape
            shape_cx = shape['x'] + shape['width'] / 2
            shape_cy = shape['y'] + shape['height'] / 2
            text['x'] = shape_cx - text_w / 2
            text['y'] = shape_cy - text_h / 2

            fixed_count += 1
            i += 2
        else:
            i += 1

    with open(filepath, 'w') as f:
        json.dump(data, f, indent=2)

    print(f"Fixed {fixed_count} text elements in {filepath}")
    return fixed_count


if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Usage: python3 fix_text_alignment.py <file.excalidraw>")
        sys.exit(1)

    fix_text_alignment(sys.argv[1])
